"use client";

import React, { useState } from "react";
import { motion } from "framer-motion";
import type { Investigation, AppTab } from "@/lib/types";
import { MOCK_REPORT } from "@/lib/mockData";

interface ReportsViewProps {
  investigation: Investigation;
  onNavigateTab: (tab: AppTab) => void;
}

export default function ReportsView({
  investigation,
  onNavigateTab,
}: ReportsViewProps) {
  const [isGenerated, setIsGenerated] = useState<boolean>(true);
  const [activeFormat, setActiveFormat] = useState<"dossier" | "markdown" | "json">("dossier");
  const report = investigation.report || MOCK_REPORT;

  const handlePrint = () => {
    window.print();
  };

  const handleDownloadJSON = () => {
    const dataStr =
      "data:text/json;charset=utf-8," +
      encodeURIComponent(JSON.stringify(report, null, 2));
    const downloadAnchor = document.createElement("a");
    downloadAnchor.setAttribute("href", dataStr);
    downloadAnchor.setAttribute(
      "download",
      `AI_Witness_Report_${investigation.id}.json`
    );
    document.body.appendChild(downloadAnchor);
    downloadAnchor.click();
    downloadAnchor.remove();
  };

  const handleDownloadMD = () => {
    const mdContent = `# AI WITNESS — FORENSIC INCIDENT REPORT
**Case ID**: #${investigation.id.toUpperCase()}
**Incident Type**: ${report.incidentType}
**Interval**: ${report.startTime} – ${report.endTime} UTC
**Location**: ${report.location}
**Overall Confidence**: ${report.overallConfidence}%

---

## 1. Executive Forensic Summary
> "${report.aiSummary}"

---

## 2. Entities Involved (Anonymous IDs Only)
${report.entitiesInvolved.map((e) => `- **${e}**`).join("\n")}

---

## 3. Chronological Reconstruction Timeline
${report.timeline.map((t) => `- **${t.timestamp}** [${t.cameraLabel}]: ${t.description} (Subject: ${t.entityLabel})`).join("\n")}

---

## 4. Observed Facts (Verified Visual Sensor Ground Truth)
${report.observedFacts.map((f) => `- [${f.timestamp}] [${f.cameraLabel}]: ${f.text} (Confidence: ${f.confidence * 100}%)`).join("\n")}

---

## 5. AI Inferences & Probability Analysis
${report.inferences.map((inf) => `- **Inference (${inf.confidence * 100}%)**: ${inf.text}`).join("\n")}

---

## 6. Disclosed Uncertainties & Sensor Limitations
${report.uncertainties.map((u) => `- ⚠️ ${u}`).join("\n")}

---
*Report Generated by AI Witness Intelligence Platform on ${report.generatedAt}*
*SHA-256 Chain of Custody Sealed*
`;

    const dataStr =
      "data:text/markdown;charset=utf-8," + encodeURIComponent(mdContent);
    const downloadAnchor = document.createElement("a");
    downloadAnchor.setAttribute("href", dataStr);
    downloadAnchor.setAttribute(
      "download",
      `AI_Witness_Report_${investigation.id}.md`
    );
    document.body.appendChild(downloadAnchor);
    downloadAnchor.click();
    downloadAnchor.remove();
  };

  return (
    <div className="p-6 space-y-6 max-w-5xl mx-auto">
      {/* Action Header */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <div className="text-xs font-mono text-amber-400 uppercase tracking-wider mb-1">
            Official Incident Dossier
          </div>
          <h2 className="text-2xl font-bold font-mono text-white">
            Forensic Incident Report
          </h2>
          <p className="text-sm text-neutral-400">
            Court-ready, explainable reconstruction report with cryptographic evidence verification.
          </p>
        </div>

        <div className="flex flex-wrap items-center gap-2">
          <button
            onClick={handlePrint}
            className="px-4 py-2 rounded-lg bg-amber-500 hover:bg-amber-400 text-black font-bold font-mono text-xs uppercase tracking-wider transition-all flex items-center gap-1.5 shadow-[0_0_15px_rgba(245,158,11,0.3)]"
          >
            <span>🖨</span> Print / PDF
          </button>
          <button
            onClick={handleDownloadMD}
            className="px-3 py-2 rounded-lg bg-neutral-900 border border-neutral-700 hover:border-neutral-500 text-neutral-200 font-mono text-xs transition-all"
          >
            Markdown (.md)
          </button>
          <button
            onClick={handleDownloadJSON}
            className="px-3 py-2 rounded-lg bg-neutral-900 border border-neutral-700 hover:border-neutral-500 text-neutral-200 font-mono text-xs transition-all"
          >
            JSON Dossier
          </button>
        </div>
      </div>

      {/* Report Document Sheet */}
      <motion.div
        initial={{ opacity: 0, y: 15 }}
        animate={{ opacity: 1, y: 0 }}
        className="rounded-2xl border border-neutral-700 bg-neutral-900/90 backdrop-blur-xl p-8 space-y-8 shadow-2xl text-neutral-200"
        id="printable-report"
      >
        {/* Letterhead */}
        <div className="flex flex-wrap justify-between items-start border-b border-neutral-700 pb-6 gap-4">
          <div className="space-y-1">
            <div className="flex items-center gap-2">
              <div className="w-5 h-5 rounded bg-amber-500 text-black font-bold text-xs flex items-center justify-center font-mono">
                W
              </div>
              <span className="font-mono text-sm font-bold tracking-widest text-white uppercase">
                AI WITNESS FORENSIC INTELLIGENCE PLATFORM
              </span>
            </div>
            <div className="text-xs font-mono text-neutral-400">
              Automated Multi-Camera Spatiotemporal Incident Reconstruction
            </div>
          </div>

          <div className="text-right font-mono text-xs space-y-0.5">
            <div className="text-amber-400 font-bold">CASE #{investigation.id.toUpperCase()}</div>
            <div className="text-neutral-500">GENERATED: {report.generatedAt}</div>
            <div className="text-emerald-400 font-semibold">STATUS: SEALED & VERIFIED</div>
          </div>
        </div>

        {/* Section 1: Incident Specification */}
        <div className="space-y-3">
          <div className="text-xs font-mono text-amber-400 font-bold uppercase tracking-wider">
            1. Incident Specification & Metadata
          </div>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-3 p-4 rounded-xl bg-neutral-950/70 border border-neutral-800 text-xs font-mono">
            <div>
              <span className="text-neutral-500">INCIDENT TYPE:</span>
              <div className="font-bold text-white mt-0.5">{report.incidentType}</div>
            </div>
            <div>
              <span className="text-neutral-500">TIME INTERVAL (UTC):</span>
              <div className="font-bold text-amber-400 mt-0.5">
                {report.startTime} – {report.endTime}
              </div>
            </div>
            <div>
              <span className="text-neutral-500">FACILITY / LOCATION:</span>
              <div className="font-bold text-neutral-200 mt-0.5">{report.location}</div>
            </div>
          </div>
        </div>

        {/* Section 2: Executive AI Summary */}
        <div className="space-y-3">
          <div className="text-xs font-mono text-amber-400 font-bold uppercase tracking-wider">
            2. Executive Synthesis & Core Findings
          </div>
          <div className="p-5 rounded-xl bg-amber-500/5 border border-amber-500/20 text-neutral-100 font-serif italic text-base leading-relaxed">
            &ldquo;{report.aiSummary}&rdquo;
          </div>
        </div>

        {/* Section 3: Entities Involved */}
        <div className="space-y-3">
          <div className="text-xs font-mono text-amber-400 font-bold uppercase tracking-wider">
            3. Anonymous Entities Involved (Zero Facial Recognition Policy)
          </div>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-3">
            {report.entitiesInvolved.map((ent, i) => (
              <div
                key={ent}
                className="p-3 rounded-lg bg-neutral-950/60 border border-neutral-800 font-mono text-xs"
              >
                <span className="text-amber-400 font-bold">{ent}</span>
                <div className="text-neutral-400 text-[11px] mt-1">
                  {i === 0
                    ? "Pedestrian subject approaching Bay 04"
                    : i === 1
                    ? "Delivery van reversing from parking stall"
                    : "Secondary bystander arriving post-incident"}
                </div>
              </div>
            ))}
          </div>
        </div>

        {/* Section 4: Chronological Reconstruction Timeline */}
        <div className="space-y-3">
          <div className="text-xs font-mono text-amber-400 font-bold uppercase tracking-wider">
            4. Chronological Reconstruction Timeline
          </div>
          <div className="border border-neutral-800 rounded-xl overflow-hidden font-mono text-xs">
            <table className="w-full text-left">
              <thead className="bg-neutral-950 text-neutral-500 border-b border-neutral-800">
                <tr>
                  <th className="p-3">TIMECODE</th>
                  <th className="p-3">CAMERA ANGLE</th>
                  <th className="p-3">ENTITY</th>
                  <th className="p-3">DESCRIPTION</th>
                  <th className="p-3 text-right">SEVERITY</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-neutral-800/60">
                {report.timeline.map((entry, idx) => (
                  <tr key={idx} className="hover:bg-neutral-800/30">
                    <td className="p-3 text-amber-400 font-bold">{entry.timestamp}</td>
                    <td className="p-3 text-neutral-300">
                      {entry.cameraLabel?.split("—")[0].trim()}
                    </td>
                    <td className="p-3 text-neutral-400">{entry.entityLabel}</td>
                    <td className="p-3 text-neutral-200 font-sans font-medium">
                      {entry.description}
                    </td>
                    <td className="p-3 text-right">
                      <span
                        className={`px-2 py-0.5 rounded text-[10px] font-bold uppercase ${
                          entry.severity === "critical"
                            ? "bg-red-500/20 text-red-400 border border-red-500/30"
                            : entry.severity === "warning"
                            ? "bg-amber-500/20 text-amber-400 border border-amber-500/30"
                            : "bg-neutral-800 text-neutral-300"
                        }`}
                      >
                        {entry.severity}
                      </span>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>

        {/* Section 5: AI Inferences vs Observed Facts */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          <div className="space-y-3">
            <div className="text-xs font-mono text-emerald-400 font-bold uppercase tracking-wider">
              5A. Observed Facts (Verified Pixels)
            </div>
            <div className="space-y-2 font-mono text-xs">
              {report.observedFacts.map((fact) => (
                <div
                  key={fact.id}
                  className="p-3 rounded-lg bg-neutral-950/60 border border-neutral-800 space-y-1"
                >
                  <div className="flex justify-between text-neutral-500 text-[10px]">
                    <span>{fact.timestamp}</span>
                    <span>{fact.cameraLabel.split("—")[0].trim()}</span>
                  </div>
                  <div className="text-neutral-200 font-sans text-xs">{fact.text}</div>
                </div>
              ))}
            </div>
          </div>

          <div className="space-y-3">
            <div className="text-xs font-mono text-amber-400 font-bold uppercase tracking-wider">
              5B. AI Inferences (Gemini Reasoning)
            </div>
            <div className="space-y-2 font-mono text-xs">
              {report.inferences.map((inf, i) => (
                <div
                  key={i}
                  className="p-3 rounded-lg bg-neutral-950/60 border border-neutral-800 space-y-1"
                >
                  <div className="flex justify-between text-amber-400 text-[10px]">
                    <span className="font-bold">INFERENCE #{i + 1}</span>
                    <span>{(inf.confidence * 100).toFixed(0)}% CONF</span>
                  </div>
                  <div className="text-neutral-200 font-sans text-xs">{inf.text}</div>
                </div>
              ))}
            </div>
          </div>
        </div>

        {/* Section 6: Disclosed Uncertainties */}
        <div className="space-y-3">
          <div className="text-xs font-mono text-red-400 font-bold uppercase tracking-wider">
            6. Disclosed Uncertainties & Sensor Blind Spots
          </div>
          <div className="space-y-2 font-mono text-xs">
            {report.uncertainties.map((u, i) => (
              <div
                key={i}
                className="p-3 rounded-lg bg-red-500/5 border border-red-500/20 text-neutral-300 text-xs flex items-start gap-2"
              >
                <span className="text-red-400 font-bold">•</span>
                <span>{u}</span>
              </div>
            ))}
          </div>
        </div>

        {/* Signature & Seal Footer */}
        <div className="pt-6 border-t border-neutral-700 flex flex-wrap justify-between items-center text-xs font-mono text-neutral-500 gap-4">
          <div>
            <div>CRYPTO CERT: SHA-256 MERKLE ROOT VALIDATED</div>
            <div className="text-[10px] text-neutral-600">
              All 4 camera streams preserved with verifiable timestamps.
            </div>
          </div>
          <div className="text-right">
            <div className="text-amber-400 font-bold">AI WITNESS ENGINE v2.4</div>
            <div className="text-[10px]">Google Gemini 1.5 Pro Spatio-Temporal Core</div>
          </div>
        </div>
      </motion.div>
    </div>
  );
}
